name: Manually deploy site 
on: workflow_dispatch

jobs:
  build:
    name: Force manually deploy production
    runs-on: ubuntu-latest
    steps:
    - name: Remove repo at clone it -> large footprint!
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.WASE_DEPLOY }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd /var/www/qwict/
          rm -rf WaseClubMain
          git clone https://github.com/Qwict/WaseClubMain.git
          cd WaseClubMain/
          git status
